//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedBackRepositoryPattern.ORM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class feedbackdatabaseEntities : DbContext
    {
        public feedbackdatabaseEntities()
            : base("name=feedbackdatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admin { get; set; }
        public DbSet<Programmers> Programmers { get; set; }
        public DbSet<Projects> Projects { get; set; }
        public DbSet<Reporter> Reporter { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
