//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedBackRepositoryPattern.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programmers
    {
        public Programmers()
        {
            this.Projects = new HashSet<Projects>();
        }
    
        public int ProgrammerID { get; set; }
        public string ProgrammerName { get; set; }
        public string ProgrammerEmail { get; set; }
        public string ProgrammerProjects { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual ICollection<Projects> Projects { get; set; }
    }
}
