//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedBackRepositoryPattern.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects
    {
        public Projects()
        {
            this.Programmers = new HashSet<Programmers>();
            this.ReportInformation = new HashSet<ReportInformation>();
        }
    
        public int ProjectID { get; set; }
        public string ProjectTitle { get; set; }
        public string ProjectExplanation { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public byte[] Image { get; set; }
    
        public virtual ICollection<Programmers> Programmers { get; set; }
        public virtual ICollection<ReportInformation> ReportInformation { get; set; }
    }
}
