//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedBackRepositoryPattern.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportInformation
    {
        public ReportInformation()
        {
            this.Projects = new HashSet<Projects>();
            this.Reporter = new HashSet<Reporter>();
        }
    
        public int ReportID { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public Nullable<int> RegardingToProgrammer { get; set; }
        public Nullable<bool> SuccessfullySendedReport { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
    
        public virtual ICollection<Projects> Projects { get; set; }
        public virtual ICollection<Reporter> Reporter { get; set; }
    }
}
