//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedBackRepositoryPattern.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reporter
    {
        public Reporter()
        {
            this.ReportInformation = new HashSet<ReportInformation>();
        }
    
        public int ReporterID { get; set; }
        public string FullName { get; set; }
        public string Company { get; set; }
        public string EmailAddress { get; set; }
        public string ContactNumber { get; set; }
    
        public virtual ICollection<ReportInformation> ReportInformation { get; set; }
    }
}
